version: "3.9"
services:
  backend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app:ro
    command: python start_backend.py --server-ip 0.0.0.0 --server-port 9000
    ports:
      - "9000:9000"

  proxy:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app:ro
    command: python start_proxy.py --server-ip 0.0.0.0 --server-port 8080
    ports:
      - "8080:8080"
    depends_on:
      - backend

  tracker:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./:/app:ro
    command: python start_sampleapp.py --server-ip 0.0.0.0 --server-port 8001
    ports:
      - "8001:8001"